# -*- coding: utf-8 -*-
"""hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mMi67kXiTNGHTuQepqafCYhnhSSSoN8l
"""

print('Hello World!')

a = 10
print(a)

print(5 + 3)

b = int(input())

print(b)